services:
  - type: web
    name: whatsapp-bot-backend
    env: node
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8081
      - key: MONGODB_URI
        value: mongodb+srv://yashshinde2151:Yashinde@21@whatsapp-bot.vi9nesr.mongodb.net/?retryWrites=true&w=majority&appName=whatsapp-bot
      - key: DASHBOARD_ORIGIN
        value: https://whatsapp-bot-one-rho.vercel.app
      - key: SESSION_DIR
        value: ./sessions
      - key: ADMIN_TOKEN
        value: whatsappbot1234
      - key: SMTP_HOST
        value: smtp.sendgrid.net
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        value: apikey
      - key: SMTP_PASS
        sync: false
    healthCheckPath: /
    autoDeploy: true
